### PR TITLE
chainguard-2.28: Test build libunistring

### PR DESCRIPTION
**Pull request by xnox**
Picked up host glibc symbol somehow for

> /home/build/lib/struniq.h:98:(.text+0xef): undefined reference to `__libc_single_threaded'

### CODE REVIEW

**Review by techalchemy — APPROVED** [review]

**Comment by xnox** [comment]
1 neutral check is still broken build on 2.28 =)
