### PR TITLE
chainguard-2.28: Test build libunwind

### PR DESCRIPTION
**Pull request by xnox**
arm64:
> ptrace/_UPT_ptrauth_insn_mask.c:38:40: error: 'NT_ARM_PAC_MASK' undeclared (first use in this function); did you mean 'EF_ARM_EABIMASK'?

### CODE REVIEW

**Review by techalchemy — APPROVED** [review]

**Comment by xnox** [comment]
1 neutral check is still broken build on 2.28 =)
